Document: sagscl
Title: Debian sagscl Manual
Author: <insert document author here>
Abstract: This manual describes what sagscl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sagscl/sagscl.sgml.gz

Format: postscript
Files: /usr/share/doc/sagscl/sagscl.ps.gz

Format: text
Files: /usr/share/doc/sagscl/sagscl.text.gz

Format: HTML
Index: /usr/share/doc/sagscl/html/index.html
Files: /usr/share/doc/sagscl/html/*.html

  
